version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  web-front:
    build:
      context: ./web-front
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - redis

  web-back:
    build:
      context: ./web-back
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis
