
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - whenfight-network

  web-back:
    build:
      context: ./web-back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - whenfight-network
  
  web-front:
    build:
      context: ./web-front
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    depends_on:
      - web_back
    networks:
      - whenfight-network
    
networks:
  whenfight-network:
